-- Database: LOS_GRANDES_ALMACENES

-- DROP DATABASE "LOS_GRANDES_ALMACENES";

CREATE DATABASE "LOS_GRANDES_ALMACENES"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Spanish_Spain.1252'
    LC_CTYPE = 'Spanish_Spain.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
	
CREATE TABLE CAJEROS(
	Cajero INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NomApels varchar(255)
);

CREATE TABLE PRODUCTOS(
	Producto INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Nombre varchar(100),
	Precio money
);
CREATE TABLE MAQUINAS_REGISTRADORAS(
	Maquina INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Piso int
);
CREATE TABLE VENTA(
	Cajero int,
	Maquina int,
	Producto int,
	CONSTRAINT fk_cajeros FOREIGN KEY(Cajero) REFERENCES CAJEROS(Cajero),
	CONSTRAINT fk_registradoras FOREIGN KEY(Maquina) REFERENCES MAQUINAS_REGISTRADORAS(Maquina),
	CONSTRAINT fk_productos FOREIGN KEY(Producto) REFERENCES PRODUCTOS(Producto)	
);